---
name: Test
on:
  push:
    branches:
      - main
    tags:
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pip install --upgrade --upgrade-strategy eager -r requirements.txt
      - run: pytest --cov-report html:cov_html --cov=cow tests/
      - uses: actions/upload-artifact@v3
        with:
          name: coverage report
          path: cov_html/
